### ISSUE TITLE
LCP is not being calculated

### ISSUE THREAD

**Issue by MeganOzanne** [cmorten/cypress-web-vitals#19]
When using cy.vitals within my cypress tests the lcp occasionally fails to be calculated. message is 'lcp web-vital could not be calculated, and threshold was 3000. Skipping...' 

Setup:

- node version: v14.17.2
- cypress-web-vitals version: latest

## Details

Our tests are setup with this code:

`cy.vitals({
    firstInputSelector: 'main',
    thresholds: { lcp: 3000, fid: 100, cls: 0.1, fcp: 1800, ttfb: 600 },
    onReport({ thresholds, results }) {
      console.log(results);
    },
  });`

When this code is hit within our tests we see

![image](https://user-images.githubusercontent.com/100417387/191727647-05402da9-4019-4f8b-9762-881294277a71.png)

As of yet, I have not been able to find a workaround or solution.

On instances where the LCP is calculated, it is not actually using the LCP, It appears to calculate based on the FCP instead.

My assumption is that our app takes so long to load cy.vitals is falling over. Extending timeouts etc does not seem to work.

I'll continue to dig as this would be a great tool to use but if you are aware of a solution please can you advise. 

The AUT is built on Angular and we are using Cypress 10

**Comment by furhan-dev** [comment]
I've also run into the same issue. LCP is never reported, but when I run lighthouse on the same url it is reported fine. Other urls (outside my app seem to work fine). 

I've also tried increasing the reporter timeout with no luck. @MeganOzanne Did you find the cause of your issue? 

FWIW I tried adding a performance observer in the cypress dev tools console and see that it captures `largest-contentful-paint`:

`new PerformanceObserver((entryList) => {
  for (const entry of entryList.getEntries()) {
    console.log('LCP candidate:', entry.startTime, entry);
  }
}).observe({type: 'largest-contentful-paint', buffered: true});`

**Comment by cmorten** [comment]
Hmm I wonder if it is a race condition, just had a look back over the code and noticed that opted for a `<script type="module">` which afaik has `defer` like behaviour

REF: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

> This value causes the code to be treated as a JavaScript module. The processing of the script contents is deferred. The charset and defer attributes have no effect. For information on using module, see our [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) guide. Unlike classic scripts, module scripts require the use of the CORS protocol for cross-origin fetching.

If LCP is lightning quick there’s a possibility this could get missed 🤔 

Pertinent code: https://github.com/cmorten/cypress-web-vitals/blob/main/src/constants.js#L26

**Comment by furhan-dev** [comment]
I'm running it against a docker container
`docker run --platform linux/arm64 -p 9000:9000 --rm cribl/cribl:next-nightly`
then `cy.visit('http://localhost:9000/login')` prior to the call to `cy.vitals(..)`

**Comment by furhan-dev** [comment]
I don't think LCP is lightening quick since I see FCP values reported at 200+ ms

**Comment by cmorten** [comment]
Got it, see https://web.dev/lcp/#when-is-largest-contentful-paint-reported

> The browser will stop reporting new entries as soon as the user interacts with the page (via a tap, scroll, or keypress), as user interaction often changes what's visible to the user (which is especially true with scrolling).

This tool interacts with the page for FID generation but this stops subsequent LCP metrics being generated. We need to hold off page interaction until after (at least) the first LCP metrics is generated.

**Comment by cmorten** [comment]
@MeganOzanne @furhan-dev can you see if https://github.com/cmorten/cypress-web-vitals/releases/tag/2.2.0 resolves the issue for you?

**Comment by furhan-dev** [comment]
@cmorten to confirm, you want me to manually update my `node_modules` with the package in the link above right? I see npm has `2.2.1` but not `2.2.2` available.

On `2.2.1` I now do sometimes see `LCP` being reported, but I also often see `FID` not being reported.
On `2.2.2` (manually copying over the module) I don't see `LCP` being reported still and same issue with `FID`

Here are the URLs I'm running against (username/pw is admin):
```json
[
  "/stream",
  "/stream/dashboard/workers",
  "/stream/inputs",
  "/stream/outputs",
  "/stream/quick-connect",
  "/stream/pipelines",
  "/stream/routes"
]
```

**Comment by furhan-dev** [comment]
Here are my dependencies from `package.json`:
```json
"devDependencies": {
    "cypress": "^12.4.1",
    "cypress-real-events": "^1.7.6",
    "cypress-web-vitals": "^2.2.1",
    "moment": "^2.29.4"
  }
```

**Comment by cmorten** [comment]
> @cmorten to confirm, you want me to manually update my `node_modules` with the package in the link above right? I see npm has `2.2.1` but not `2.2.2` available.
> 
> On `2.2.1` I now do sometimes see `LCP` being reported, but I also often see `FID` not being reported. On `2.2.2` (manually copying over the module) I don't see `LCP` being reported still and same issue with `FID`
> 
> Here are the URLs I'm running against (username/pw is admin):
> 
> ```json
> [
>   "/stream",
>   "/stream/dashboard/workers",
>   "/stream/inputs",
>   "/stream/outputs",
>   "/stream/quick-connect",
>   "/stream/pipelines",
>   "/stream/routes"
> ]
> ```

Apologies think might have confused things - I released a potential fix as version `2.2.0` for you test against (with a package.json update and yarn/npm install) and then also released a no-op `2.2.1` to update the README to match the changes. Either version should suffice to test if your issue with LCP not being recorded was resolved. There isn't a `2.2.2` 🙂 (I guess that would be the HEAD of main, but this is the same as `2.2.1` afaik atm!)

From your `2.2.1` mileage it sounds like we're not 100% there (but perhaps better?) - I can take another look to see if can get LCP reporting more reliable (open to ideas / PRs if have an idea).

For FID, can you see if providing a custom `firstInputSelector` option yeilds more consistent results? Typically FID is reported when an interaction occurs with something that fires an event - the default of the `body` is often good enough as there is often some event handler that will capture clicks, but not always - if there's a non-submitting form field / element with an event handler on the page that can be used then would recommend passing it's selector for this option.

**Comment by furhan-dev** [comment]
@cmorten I tried the default `firstInputSelector` as well as selecting on `#root` and still see `fid` null sometimes. I mostly see `lcp` null but sometimes it reports now (which is an improvement). 

Here is some sample data from the report (note: I changed around some of the reported numbers here):
```
  {
    "endpoint": "/stream",
    "lcp": null,
    "fid": 1.2,
    "cls": 0.000015076772657815239,
    "fcp": 221.5,
    "ttfb": 25.60000002384186
  },
  {
    "endpoint": "/stream/dashboard/workers",
    "lcp": null,
    "fid": 0.6999999761581421,
    "cls": 0.00014487133228592747,
    "fcp": 444,
    "ttfb": 11.100000023841858
  },
  {
    "endpoint": "/stream/inputs",
    "lcp": 379.3,
    "fid": null,
    "cls": 0.000003222924517319371,
    "fcp": 379.3000000119209,
    "ttfb": 7.900000035762787
  }
```

Do you seem similar issues when you try to run vitals against these URLs?

**Comment by furhan-dev** [comment]
I've noticed that when it does report `lcp`, `vitals()` doesn't wait for the `vitalsReportedTimeout`. That is, I notice the metrics reported immediately on page load and the test runner moves onto the next test.

Should `vitals()` wait the full `vitalsReportedTimeout` before reporting? I would assume so since there may still be elements loading.

**Comment by cmorten** [comment]
> Should `vitals()` wait the full `vitalsReportedTimeout` before reporting? I would assume so since there may still be elements loading.

That's not quite it's behaviour no, this timeout is for waiting for all the expected vitals to have at least one recorded entry. If all metrics are reported before the timeout then it will exit out early.

I could look into providing a different "wait" mechanism, but arbitrary waits are not ideal.

Instead what I suspect will resolve this issue is #25 where new commands are being introduced where you can start an audit, perform your own commands, checks, etc. and then generate a report. This provides the consumer more control over actions that will result in all the vitals being reported as the "batteries included" current `cy.vitals()` command doesn't always meet all use-cases.

**Comment by salazarm** [comment]
I'm running into this same issue 😬
